### ISSUE TITLE
PDF

### ISSUE THREAD

**Issue by JudsonArtur** [vendus/vendus-sdk-php#2]
Olá Bom dia, quero saber qual framework ou library o vendus usar para imprimir PDF, sou desenvolvedor principiante e acho aquilo fantástico, podem ajudar-me?

**Comment by fgonga** [comment]
Olá judson  acredito ser o 
https://github.com/dompdf/dompdf
quem conhece o laravel tem o:
https://github.com/barryvdh/laravel-dompdf
